// prettier-ignore
const LegendsFilters = [
    "Cyclops",
	"Golem",
	"Spectre",
	"Rock Troll",
	"Slurg Beast",
	"Beholder",
	"Chaos Knight",
	"Hydra",
	"Centaur",
	"Skeleton King",
	"Genie",
	"Faabian",
	"Minotaur",
	"Medusa",
	"Black Knight",
	"Dark Lord",
	"Green Dragon",
	"Red Dragon",
	"Giant Scorpion",
	"Frost Demon",
	"Golden Golem",
	"Madcanic",
	"Frost Dragon",
	"Giant Frog",
	"Fire Beast",
	"Babbeh",	
	"Giant Widow",
	"King Cobra",
	"Lava Lizard",
	"Cave Troll",
	"Mighty Dragon",
	"Squeeerg",
	"Treent",
	"Giant Guard",
	"Plaguemaster",
	"Witch Doctor",
	"Mazor",
	"Holy Knight",
	"Slime Ghost",
	"Clay Golem",
	"Giant Lizard",
	"Cowled Lizard",
	"Raiseling",
	"Smorag",
	"Deathbringer"
];

export default LegendsFilters;
